// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state_machine/states/awaiting_info.dart';
import 'state_machine/types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustPaymentApi>>
abstract class RustPaymentApi implements RustOpaqueInterface {
  /// Cancela o pagamento atual
  Future<String> cancelPayment();

  /// Completa o pagamento com sucesso
  Future<String> completePayment({required String transactionId, required String authorizationCode});

  /// Confirma as informações e inicia o pagamento
  Future<String> confirmInfo();

  static Future<RustPaymentApi> default_() => RustLib.instance.api.crateApiRustPaymentApiDefault();

  /// Obtém descrição do estado AwaitingInfo
  Future<String> getAwaitingInfoDescription();

  /// Retorna o estado atual
  Future<StateType> getCurrentState();

  /// Obtém descrição do estado EMVPayment
  Future<String> getEmvPaymentDescription();

  /// Obtém descrição do estado PaymentSuccess
  Future<String> getPaymentSuccessDescription();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Cria uma nova instância da API
  static Future<RustPaymentApi> newInstance() => RustLib.instance.api.crateApiRustPaymentApiNew();

  /// Processa o pagamento EMV
  Future<String> processPayment();

  /// Define o valor do pagamento
  Future<String> setAmount({required double amount});

  /// Define o tipo de pagamento
  Future<String> setPaymentType({required PaymentType paymentType});
}
