// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state_machine/states/awaiting_info.dart';
import 'state_machine/types.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 86017426;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'rust_payment_engine',
    ioDirectory: 'rust_payment_engine/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiRustPaymentApiCancelPayment({required RustPaymentApi that});

  Future<String> crateApiRustPaymentApiCompletePayment({
    required RustPaymentApi that,
    required String transactionId,
    required String authorizationCode,
  });

  Future<String> crateApiRustPaymentApiConfirmInfo({required RustPaymentApi that});

  Future<RustPaymentApi> crateApiRustPaymentApiDefault();

  Future<String> crateApiRustPaymentApiGetAwaitingInfoDescription({required RustPaymentApi that});

  Future<StateType> crateApiRustPaymentApiGetCurrentState({required RustPaymentApi that});

  Future<String> crateApiRustPaymentApiGetEmvPaymentDescription({required RustPaymentApi that});

  Future<String> crateApiRustPaymentApiGetPaymentSuccessDescription({required RustPaymentApi that});

  Future<RustPaymentApi> crateApiRustPaymentApiNew();

  Future<String> crateApiRustPaymentApiProcessPayment({required RustPaymentApi that});

  Future<String> crateApiRustPaymentApiSetAmount({required RustPaymentApi that, required double amount});

  Future<String> crateApiRustPaymentApiSetPaymentType({required RustPaymentApi that, required PaymentType paymentType});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RustPaymentApi;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RustPaymentApi;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RustPaymentApiPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiRustPaymentApiCancelPayment({required RustPaymentApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiCancelPaymentConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiCancelPaymentConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_cancel_payment", argNames: ["that"]);

  @override
  Future<String> crateApiRustPaymentApiCompletePayment({
    required RustPaymentApi that,
    required String transactionId,
    required String authorizationCode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          sse_encode_String(transactionId, serializer);
          sse_encode_String(authorizationCode, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiCompletePaymentConstMeta,
        argValues: [that, transactionId, authorizationCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiCompletePaymentConstMeta => const TaskConstMeta(
    debugName: "RustPaymentApi_complete_payment",
    argNames: ["that", "transactionId", "authorizationCode"],
  );

  @override
  Future<String> crateApiRustPaymentApiConfirmInfo({required RustPaymentApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiConfirmInfoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiConfirmInfoConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_confirm_info", argNames: ["that"]);

  @override
  Future<RustPaymentApi> crateApiRustPaymentApiDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRustPaymentApiDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiDefaultConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_default", argNames: []);

  @override
  Future<String> crateApiRustPaymentApiGetAwaitingInfoDescription({required RustPaymentApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiGetAwaitingInfoDescriptionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiGetAwaitingInfoDescriptionConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_get_awaiting_info_description", argNames: ["that"]);

  @override
  Future<StateType> crateApiRustPaymentApiGetCurrentState({required RustPaymentApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_state_type, decodeErrorData: null),
        constMeta: kCrateApiRustPaymentApiGetCurrentStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiGetCurrentStateConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_get_current_state", argNames: ["that"]);

  @override
  Future<String> crateApiRustPaymentApiGetEmvPaymentDescription({required RustPaymentApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiGetEmvPaymentDescriptionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiGetEmvPaymentDescriptionConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_get_emv_payment_description", argNames: ["that"]);

  @override
  Future<String> crateApiRustPaymentApiGetPaymentSuccessDescription({required RustPaymentApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiGetPaymentSuccessDescriptionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiGetPaymentSuccessDescriptionConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_get_payment_success_description", argNames: ["that"]);

  @override
  Future<RustPaymentApi> crateApiRustPaymentApiNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRustPaymentApiNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiNewConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_new", argNames: []);

  @override
  Future<String> crateApiRustPaymentApiProcessPayment({required RustPaymentApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiProcessPaymentConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiProcessPaymentConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_process_payment", argNames: ["that"]);

  @override
  Future<String> crateApiRustPaymentApiSetAmount({required RustPaymentApi that, required double amount}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          sse_encode_f_64(amount, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiSetAmountConstMeta,
        argValues: [that, amount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiSetAmountConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_set_amount", argNames: ["that", "amount"]);

  @override
  Future<String> crateApiRustPaymentApiSetPaymentType({
    required RustPaymentApi that,
    required PaymentType paymentType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
            that,
            serializer,
          );
          sse_encode_payment_type(paymentType, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiRustPaymentApiSetPaymentTypeConstMeta,
        argValues: [that, paymentType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRustPaymentApiSetPaymentTypeConstMeta =>
      const TaskConstMeta(debugName: "RustPaymentApi_set_payment_type", argNames: ["that", "paymentType"]);

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RustPaymentApi =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RustPaymentApi =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi;

  @protected
  RustPaymentApi dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustPaymentApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustPaymentApi dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustPaymentApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustPaymentApi dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustPaymentApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PaymentType dco_decode_payment_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PaymentType.values[raw as int];
  }

  @protected
  StateType dco_decode_state_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StateType.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  RustPaymentApi sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustPaymentApiImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustPaymentApi sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustPaymentApiImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustPaymentApi sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustPaymentApiImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PaymentType sse_decode_payment_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PaymentType.values[inner];
  }

  @protected
  StateType sse_decode_state_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StateType.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    RustPaymentApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as RustPaymentApiImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    RustPaymentApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as RustPaymentApiImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustPaymentApi(
    RustPaymentApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as RustPaymentApiImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_payment_type(PaymentType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_state_type(StateType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class RustPaymentApiImpl extends RustOpaque implements RustPaymentApi {
  // Not to be used by end users
  RustPaymentApiImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RustPaymentApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_RustPaymentApi,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_RustPaymentApi,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_RustPaymentApiPtr,
  );

  /// Cancela o pagamento atual
  Future<String> cancelPayment() => RustLib.instance.api.crateApiRustPaymentApiCancelPayment(that: this);

  /// Completa o pagamento com sucesso
  Future<String> completePayment({required String transactionId, required String authorizationCode}) =>
      RustLib.instance.api.crateApiRustPaymentApiCompletePayment(
        that: this,
        transactionId: transactionId,
        authorizationCode: authorizationCode,
      );

  /// Confirma as informações e inicia o pagamento
  Future<String> confirmInfo() => RustLib.instance.api.crateApiRustPaymentApiConfirmInfo(that: this);

  /// Obtém descrição do estado AwaitingInfo
  Future<String> getAwaitingInfoDescription() =>
      RustLib.instance.api.crateApiRustPaymentApiGetAwaitingInfoDescription(that: this);

  /// Retorna o estado atual
  Future<StateType> getCurrentState() => RustLib.instance.api.crateApiRustPaymentApiGetCurrentState(that: this);

  /// Obtém descrição do estado EMVPayment
  Future<String> getEmvPaymentDescription() =>
      RustLib.instance.api.crateApiRustPaymentApiGetEmvPaymentDescription(that: this);

  /// Obtém descrição do estado PaymentSuccess
  Future<String> getPaymentSuccessDescription() =>
      RustLib.instance.api.crateApiRustPaymentApiGetPaymentSuccessDescription(that: this);

  /// Processa o pagamento EMV
  Future<String> processPayment() => RustLib.instance.api.crateApiRustPaymentApiProcessPayment(that: this);

  /// Define o valor do pagamento
  Future<String> setAmount({required double amount}) =>
      RustLib.instance.api.crateApiRustPaymentApiSetAmount(that: this, amount: amount);

  /// Define o tipo de pagamento
  Future<String> setPaymentType({required PaymentType paymentType}) =>
      RustLib.instance.api.crateApiRustPaymentApiSetPaymentType(that: this, paymentType: paymentType);
}
